// Generated by CoffeeScript 1.10.0
(function() {
  var resizeWindow;

  document.on("DOMContentLoaded", function(event) {
    return document.query("a.window").forEach(resizeWindow);
  });

  window.onresize = function() {
    return document.query("a.window").forEach(resizeWindow);
  };

  resizeWindow = function(aWindow) {
    aWindow.style.width = "25%";
    return aWindow.style.height = (window.innerHeight * (1 / 2)) + "px";
  };

}).call(this);
