// Generated by CoffeeScript 1.10.0
(function() {
  window.instruments = [];

  window.instruments.push({
    "identifier": "S0423721",
    "serial number": "S0423721",
    "make": "Peavey",
    "model": "Rage 158",
    "function": "Guitar Amplifier",
    "year": 2004,
    "price": 44,
    "output": "15 watts",
    "summary": "A reliable and good sounding 15 watt guitar amplifier.\n\nIt has two channels: a clean channel and a distortion channel. The distortion channel has a pre-gain and post-gain controls so that you can dial in the amount of distortion that you want at a comfortable volume.\n\nThree band EQ (bass, middle, treble) with modern and vintage modes. We usually keep it on the vintage mode but it is always nice to have sonic options at your fingertips.\n\nOne mono input for your electric guitar, one stereo input to play songs from your iPod, and a stereo output for headphones.\n\n8 inch Blue Marvel speaker.\n\nOpen back cabinet in very good condition.\n\nPlease <a href=\"mailto:instruments@paintedturtle.xyz\">send us a note</a> if you have any questions or to schedule a time to play it."
  });

}).call(this);
